"""Add user relationship to Donation

Revision ID: 98419035d886
Revises: d4bd515d6d3e
Create Date: 2025-05-18 15:27:26.159261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98419035d886'
down_revision = 'd4bd515d6d3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_donation_user_id_user', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_constraint('fk_donation_user_id_user', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
